const GuildAdapter = {
  guild: (guild) => {
    return {
      guild: {
        'id': guild.id,
        'name': guild.name,
        'icon': guild.icon,
        'features': guild.features,
        'commands': guild.commands,
        'members': guild.members,
        'channels': guild.channels,
        'bans': guild.bans,
        'roles': guild.roles,
        'stageInstances': guild.stageInstances,
        'invites': guild.invites,
        'scheduledEvents': guild.scheduledEvents,
        'autoModerationRules': guild.autoModerationRules,
        'shardId': guild.shardId,
        'splash': guild.splash,
        'banner': guild.banner,
        'description': guild.description,
        'verificationLevel': guild.verificationLevel,
        'vanityURLCode': guild.vanityURLCode,
        'nsfwLevel': guild.nsfwLevel,
        'premiumSubscriptionCount': guild.premiumSubscriptionCount,
        'discoverySplash': guild.discoverySplash,
        'memberCount': guild.memberCount,
        'large': guild.large,
        'premiumProgressBarEnabled': guild.premiumProgressBarEnabled,
        'applicationId': guild.applicationId,
        'afkTimeout': guild.afkTimeout,
        'afkChannelId': guild.afkChannelId,
        'systemChannelId': guild.systemChannelId,
        'premiumTier': guild.premiumTier,
        'widgetEnabled': guild.widgetEnabled,
        'widgetChannelId': guild.widgetChannelId,
        'explicitContentFilter': guild.explicitContentFilter,
        'mfaLevel': guild.mfaLevel,
        'joinedTimestamp': guild.joinedTimestamp,
        'defaultMessageNotifications': guild.defaultMessageNotifications,
        'systemChannelFlags': guild.systemChannelFlags,
        'maximumMembers': guild.maximumMembers,
        'maximumPresences': guild.maximumPresences,
        'maxVideoChannelUsers': guild.maxVideoChannelUsers,
        'maxStageVideoChannelUsers': guild.maxStageVideoChannelUsers,
        'approximateMemberCount': guild.approximateMemberCount,
        'approximatePresenceCount': guild.approximatePresenceCount,
        'vanityURLUses': guild.vanityURLUses,
        'rulesChannelId': guild.rulesChannelId,
        'publicUpdatesChannelId': guild.publicUpdatesChannelId,
        'preferredLocale': guild.preferredLocale,
        'safetyAlertsChannelId': guild.safetyAlertsChannelId,
        'ownerId': guild.ownerId,
        'emojis': guild.emojis,
        'stickers': guild.stickers,
        'createdTimestamp': guild.createdTimestamp,
        'nameAcronym': guild.nameAcronym,
        'iconURL': guild.iconURL,
        'splashURL': guild.splashURL,
        'discoverySplashURL': guild.discoverySplashURL,
        'bannerURL': guild.bannerURL
      },
      isSetup: guild.isSetup,
      botRolesIds: guild.botRolesIds ?? [],
    };
  },

};
